export const MOCK_RESTAURANTS = [
  { id: "r1", name: "White Rabbit", slug: "white-rabbit", description: "Один из самых известных ресторанов Москвы, расположенный на 16-м этаже здания на Смоленской площади. Шеф-повар Владимир Мухин создает уникальные блюда высокой русской кухни, переосмысливая традиционные рецепты с использованием локальных сезонных продуктов. Панорамные окна открывают захватывающий вид на центр столицы.", shortDesc: "Ресторан высокой русской кухни с панорамным видом", cuisine: ["RUSSIAN","FUSION"], priceRange: "LUXURY", city: "Москва", address: "Смоленская пл., 3, 16-й этаж", avgRating: 4.8, reviewCount: 2847, openingTime: "12:00", closingTime: "00:00", features: ["vip","terrace","parking"], coverImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=75", depositRequired: true, depositAmount: 5000, maxPartySize: 10, tables: [{id:"t1",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"},{id:"t2",label:"VIP",minCapacity:2,maxCapacity:8,tableType:"VIP"}] },
  { id: "r2", name: "Selfie", slug: "selfie", description: "Ресторан авторской кухни Анатолия Казакова, отмеченный звездой Michelin. Меню построено на принципах новой русской кухни с акцентом на локальные продукты и современные техники приготовления. Каждое блюдо продуман как произведение гастрономического искусства.", shortDesc: "Авторская кухня Анатолия Казакова", cuisine: ["RUSSIAN","FUSION"], priceRange: "LUXURY", city: "Москва", address: "Новинский бул., 31", avgRating: 4.7, reviewCount: 1923, openingTime: "12:00", closingTime: "00:00", features: ["vip","private_room"], coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=75", depositRequired: true, depositAmount: 3000, maxPartySize: 8, tables: [{id:"t3",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r3", name: "Twins Garden", slug: "twins-garden", description: "Гастрономический ресторан братьев-близнецов Ивана и Сергея Березуцких, входящий в рейтинг The Worlds 50 Best Restaurants. Уникальная концепция farm-to-table с собственной фермой и лабораторией ферментации. Дегустационный сет из 12 подач.", shortDesc: "Гастрономический ресторан братьев Березуцких", cuisine: ["RUSSIAN","FUSION"], priceRange: "LUXURY", city: "Москва", address: "Страстной бул., 8а", avgRating: 4.9, reviewCount: 1456, openingTime: "18:00", closingTime: "00:00", features: ["tasting_menu","wine_pairing","vip"], coverImage: "https://images.unsplash.com/photo-1560053608-13721e0d69e8?w=600&q=75", depositRequired: true, depositAmount: 7000, maxPartySize: 6, tables: [{id:"t4",label:"1",minCapacity:2,maxCapacity:4,tableType:"VIP"}] },
  { id: "r4", name: "Белуга", slug: "beluga", description: "Легендарный ресторан при отеле Националь с видом на Кремль. Классическая русская кухня с элементами модернизации. Фирменная черная икра, осетрина, стерлядь и отборные морепродукты в роскошном интерьере с живой музыкой.", shortDesc: "Легендарный ресторан русской кухни", cuisine: ["RUSSIAN","SEAFOOD"], priceRange: "LUXURY", city: "Москва", address: "ул. Тверская, 15", avgRating: 4.8, reviewCount: 2134, openingTime: "12:00", closingTime: "00:00", features: ["vip","terrace","live_music","parking"], coverImage: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=75", depositRequired: true, depositAmount: 3000, maxPartySize: 10, tables: [{id:"t5",label:"1",minCapacity:2,maxCapacity:2,tableType:"STANDARD"},{id:"t6",label:"VIP-1",minCapacity:2,maxCapacity:8,tableType:"VIP"}] },
  { id: "r5", name: "Пушкинъ", slug: "pushkin", description: "Культовый ресторан, воссоздающий атмосферу русского дворянского клуба XIX века. Три этажа с уникальными интерьерами: библиотека, аптека и бальный зал. Меню классической русской кухни с легендарными блинами, пожарскими котлетами и десертами.", shortDesc: "Классика русской кухни в интерьере XIX века", cuisine: ["RUSSIAN"], priceRange: "PREMIUM", city: "Москва", address: "Тверской бул., 26а", avgRating: 4.6, reviewCount: 4521, openingTime: "12:00", closingTime: "00:00", features: ["vip","parking","live_music"], coverImage: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&q=75", depositRequired: true, depositAmount: 2000, maxPartySize: 12, tables: [{id:"t7",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r6", name: "Сахалин", slug: "sakhalin", description: "Ресторан морепродуктов премиум-класса с акцентом на продукты Дальнего Востока. Свежайшие крабы, креветки и рыба доставляются ежедневно прямым рейсом из Владивостока. Открытая кухня позволяет наблюдать за мастерством шефа.", shortDesc: "Лучшие морепродукты Дальнего Востока", cuisine: ["SEAFOOD","RUSSIAN"], priceRange: "LUXURY", city: "Москва", address: "Смоленская пл., 3", avgRating: 4.7, reviewCount: 1876, openingTime: "12:00", closingTime: "00:00", features: ["vip","private_room"], coverImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=75", depositRequired: true, depositAmount: 3000, maxPartySize: 8, tables: [{id:"t8",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r7", name: "Турандот", slug: "turandot", description: "Один из самых дорогих ресторанов Москвы, интерьер которого создавался 6 лет. Роскошное барочное убранство с позолотой, фресками и хрусталем. Паназиатская кухня с элементами китайской и японской кулинарных традиций.", shortDesc: "Роскошный ресторан в стиле барокко", cuisine: ["FUSION","CHINESE","JAPANESE"], priceRange: "LUXURY", city: "Москва", address: "Тверской бул., 26", avgRating: 4.5, reviewCount: 3245, openingTime: "12:00", closingTime: "00:00", features: ["vip","parking","live_music","private_room"], coverImage: "https://images.unsplash.com/photo-1544148103-0773bf10d330?w=600&q=75", depositRequired: true, depositAmount: 5000, maxPartySize: 12, tables: [{id:"t9",label:"1",minCapacity:2,maxCapacity:6,tableType:"STANDARD"}] },
  { id: "r8", name: "Бараshka", slug: "barashka", description: "Аутентичная азербайджанская кухня в уютном ресторане на Патриарших прудах. Фирменный кебаб, садж, пити и свежая выпечка из тандыра. Летняя веранда с видом на пруды создает особую атмосферу.", shortDesc: "Азербайджанская кухня на Патриарших", cuisine: ["GEORGIAN"], priceRange: "PREMIUM", city: "Москва", address: "Спиридоньевский пер., 12/9", avgRating: 4.6, reviewCount: 2156, openingTime: "12:00", closingTime: "00:00", features: ["terrace","private_room"], coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=75", depositRequired: false, maxPartySize: 10, tables: [{id:"t10",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r9", name: "Рыбы нет", slug: "ryby-net", description: "Современная рыбная гастрономия в стильном пространстве на Красносельской. Свежайшая рыба и морепродукты от лучших поставщиков, открытая кухня, где можно наблюдать за работой шефа. Летняя веранда для романтических ужинов.", shortDesc: "Современная рыбная гастрономия", cuisine: ["SEAFOOD","FUSION"], priceRange: "PREMIUM", city: "Москва", address: "ул. Верхняя Красносельская, 3а", avgRating: 4.5, reviewCount: 987, openingTime: "12:00", closingTime: "23:00", features: ["terrace"], coverImage: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=600&q=75", depositRequired: false, maxPartySize: 8, tables: [{id:"t11",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r10", name: "Кафе Пушкинъ", slug: "cafe-pushkin", description: "Легендарная кондитерская при одноименном ресторане. Французские круассаны, эклеры и пирожные ручной работы. Утренние завтраки с видом на Тверской бульвар стали визитной карточкой заведения.", shortDesc: "Кондитерская с легендарными десертами", cuisine: ["RUSSIAN","FRENCH"], priceRange: "PREMIUM", city: "Москва", address: "Тверской бул., 26а", avgRating: 4.4, reviewCount: 3876, openingTime: "08:00", closingTime: "23:00", features: ["terrace","family_friendly"], coverImage: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=75", depositRequired: false, maxPartySize: 6, tables: [{id:"t12",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r11", name: "Честная кухня", slug: "chestnaya-kuhnya", description: "Семейный ресторан с акцентом на фермерские продукты и сезонное меню. Прямые поставки с органических ферм Подмосковья, открытая кухня и теплая домашняя атмосфера. Популярный выбор для воскресных семейных обедов.", shortDesc: "Фермерские продукты, сезонное меню", cuisine: ["RUSSIAN"], priceRange: "MODERATE", city: "Москва", address: "Садовая-Черногрязская, 10", avgRating: 4.5, reviewCount: 1234, openingTime: "10:00", closingTime: "23:00", features: ["family_friendly","terrace"], coverImage: "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=600&q=75", depositRequired: false, maxPartySize: 8, tables: [{id:"t13",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r12", name: "Nobu Moscow", slug: "nobu-moscow", description: "Московский филиал всемирно известной ресторанной империи Нобу Мацухисы. Авторская японская кухня с перуанскими акцентами. Фирменная Black Cod in Miso, суши и сашими из рыбы premium-класса. Коллекция редких сакэ.", shortDesc: "Японская кухня с перуанскими мотивами", cuisine: ["JAPANESE","FUSION"], priceRange: "LUXURY", city: "Москва", address: "Б. Дмитровка, 20/5", avgRating: 4.6, reviewCount: 1567, openingTime: "12:00", closingTime: "00:00", features: ["vip","sushi_bar","sake_collection"], coverImage: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=75", depositRequired: true, depositAmount: 4000, maxPartySize: 8, tables: [{id:"t14",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r13", name: "Сыроварня", slug: "syrovarnya", description: "Ресторан с собственной сыроварней на территории бывшего Бадаевского завода. Свежая моцарелла, буррата и рикотта приготовленные прямо при вас. Итальянская кухня с акцентом на сырные блюда, пасту и пиццу на закваске.", shortDesc: "Итальянская кухня с собственной сыроварней", cuisine: ["ITALIAN"], priceRange: "MODERATE", city: "Москва", address: "Бадаевский завод, 2", avgRating: 4.3, reviewCount: 2876, openingTime: "10:00", closingTime: "00:00", features: ["terrace","family_friendly","parking"], coverImage: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=75", depositRequired: false, maxPartySize: 10, tables: [{id:"t15",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r14", name: "Северяне", slug: "severyane", description: "Ресторан северной кухни с открытым огнем и живым огнем. Гриль и печь являются центральными элементами концепции. Авторские блюда из дичи, грибов и дикоросов. Впечатляющая винная карта от сомелье.", shortDesc: "Северная кухня с открытым огнем", cuisine: ["RUSSIAN","FUSION"], priceRange: "PREMIUM", city: "Москва", address: "Б. Никитская, 12", avgRating: 4.7, reviewCount: 876, openingTime: "12:00", closingTime: "00:00", features: ["vip","wine_list"], coverImage: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&q=75", depositRequired: true, depositAmount: 2000, maxPartySize: 6, tables: [{id:"t16",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r15", name: "Москва-Сити 354", slug: "354-exclusive", description: "Самый высокий ресторан Европы, расположенный на 86-м этаже небоскреба OKO в Москва-Сити. Панорамный вид на 360 градусов, авторская кухня фьюжн с французскими корнями. Живая музыка и VIP-зоны для закрытых мероприятий.", shortDesc: "Высотный ресторан на 86-м этаже", cuisine: ["FUSION","FRENCH"], priceRange: "LUXURY", city: "Москва", address: "Пресненская наб., 12, 86 этаж", avgRating: 4.5, reviewCount: 1654, openingTime: "12:00", closingTime: "02:00", features: ["vip","terrace","parking","live_music"], coverImage: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=75", depositRequired: true, depositAmount: 5000, maxPartySize: 8, tables: [{id:"t17",label:"1",minCapacity:2,maxCapacity:4,tableType:"VIP"}] },
  { id: "r16", name: "Хинкальная", slug: "hinkalnaya", description: "Уютная грузинская кухня с хинкали ручной лепки по семейным рецептам. Более 15 видов начинок, аутентичные грузинские вина из семейных виноделен Кахетии. Идеальное место для дружеских посиделок и семейных ужинов.", shortDesc: "Грузинская кухня с хинкали ручной лепки", cuisine: ["GEORGIAN"], priceRange: "BUDGET", city: "Москва", address: "ул. Покровка, 28", avgRating: 4.4, reviewCount: 3456, openingTime: "10:00", closingTime: "23:00", features: ["family_friendly","group_events"], coverImage: "https://images.unsplash.com/photo-1515669097368-22e68427d265?w=600&q=75", depositRequired: false, maxPartySize: 20, tables: [{id:"t18",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r17", name: "Недальний Восток", slug: "nedalniy-vostok", description: "Паназиатский ресторан в центре Москвы с авторской интерпретацией блюд Китая, Японии и Вьетнама. Dim sum, утка по-пекински и wok-блюда в современном прочтении. Приватные залы для деловых встреч.", shortDesc: "Паназиатская кухня в центре Москвы", cuisine: ["CHINESE","JAPANESE","FUSION"], priceRange: "PREMIUM", city: "Москва", address: "Тверской бул., 15", avgRating: 4.4, reviewCount: 2134, openingTime: "12:00", closingTime: "00:00", features: ["private_room","sushi_bar"], coverImage: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&q=75", depositRequired: true, depositAmount: 2000, maxPartySize: 10, tables: [{id:"t19",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r18", name: "Рыба мечты", slug: "ryba-mechty", description: "Средиземноморский ресторан морепродуктов с витриной свежей рыбы и моллюсков. Гости могут выбрать рыбу и способ приготовления: гриль, на пару или в соли. Обширная карта белых и розовых вин.", shortDesc: "Средиземноморские морепродукты", cuisine: ["SEAFOOD","ITALIAN"], priceRange: "PREMIUM", city: "Москва", address: "ул. Новый Арбат, 36", avgRating: 4.3, reviewCount: 1567, openingTime: "12:00", closingTime: "00:00", features: ["terrace","wine_list"], coverImage: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&q=75", depositRequired: false, maxPartySize: 8, tables: [{id:"t20",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r19", name: "Uhvat", slug: "uhvat", description: "Камерный ресторан с русской печью, воспроизводящий традиции деревенской кухни. Фермерские продукты, блюда томленые в чугунках, домашний хлеб на закваске. Уютная атмосфера загородного дома в центре Москвы.", shortDesc: "Русская печь и фермерские продукты", cuisine: ["RUSSIAN"], priceRange: "PREMIUM", city: "Москва", address: "Пречистенка, 10/2", avgRating: 4.6, reviewCount: 654, openingTime: "12:00", closingTime: "23:00", features: ["private_room"], coverImage: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=600&q=75", depositRequired: true, depositAmount: 1500, maxPartySize: 8, tables: [{id:"t21",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r20", name: "Мясо & Рыба", slug: "myaso-ryba", description: "Современный гастробар специализирующийся на стейках сухой выдержки и свежих устрицах. Собственная камера dry-aging, отборный мрамор из Аргентины и Австралии. Винный погреб с 400 наименованиями.", shortDesc: "Стейки на гриле и свежие устрицы", cuisine: ["STEAKHOUSE","SEAFOOD"], priceRange: "PREMIUM", city: "Москва", address: "ул. Остоженка, 1", avgRating: 4.3, reviewCount: 2345, openingTime: "12:00", closingTime: "00:00", features: ["terrace","wine_cellar","parking"], coverImage: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=75", depositRequired: true, depositAmount: 1000, maxPartySize: 12, tables: [{id:"t22",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r21", name: "Горыныч", slug: "gorynych", description: "Популярный ресторан на Патриарших прудах с русской печью и живым огнем. Концепция shared dining: блюда для совместного потребления. Летняя веранда считается одной из лучших в городе.", shortDesc: "Русская печь и живой огонь на Патриках", cuisine: ["RUSSIAN","FUSION"], priceRange: "PREMIUM", city: "Москва", address: "Спиридоньевский пер., 9/1", avgRating: 4.4, reviewCount: 1876, openingTime: "12:00", closingTime: "00:00", features: ["terrace","live_music"], coverImage: "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=600&q=75", depositRequired: false, maxPartySize: 8, tables: [{id:"t23",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r22", name: "Erwin", slug: "erwin", description: "Авторский ресторан речной рыбы и устриц в стильном лофт-пространстве. Уникальная концепция: осетр, стерлядь и сом в современном прочтении. Популярные бранчи по выходным с живой музыкой.", shortDesc: "Речная рыба и устрицы в лофте", cuisine: ["SEAFOOD","RUSSIAN"], priceRange: "PREMIUM", city: "Москва", address: "Кутузовский пр., 2/1", avgRating: 4.5, reviewCount: 1345, openingTime: "12:00", closingTime: "00:00", features: ["terrace","wine_list"], coverImage: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&q=75", depositRequired: false, maxPartySize: 8, tables: [{id:"t24",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r23", name: "Pinch", slug: "pinch", description: "Камерный fine dining ресторан с дегустационным меню из 8 подач. Каждое блюдо является авторской интерпретацией русских кулинарных традиций. Парные вина подобраны сомелье к каждой подаче.", shortDesc: "Современная российская кухня", cuisine: ["RUSSIAN","FUSION"], priceRange: "PREMIUM", city: "Москва", address: "Б. Грузинская, 69", avgRating: 4.7, reviewCount: 567, openingTime: "12:00", closingTime: "00:00", features: ["tasting_menu","wine_pairing"], coverImage: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=600&q=75", depositRequired: true, depositAmount: 3000, maxPartySize: 6, tables: [{id:"t25",label:"1",minCapacity:2,maxCapacity:4,tableType:"VIP"}] },
  { id: "r24", name: "La Maree", slug: "la-maree", description: "Ресторан французской кухни с акцентом на морепродукты. Устрицы, лобстеры и рыба доставляются ежедневно из Бретани и Средиземноморья. Приватные залы для деловых ужинов и семейных торжеств.", shortDesc: "Французская кухня с морепродуктами", cuisine: ["FRENCH","SEAFOOD"], priceRange: "LUXURY", city: "Москва", address: "ул. Петровка, 28/2", avgRating: 4.5, reviewCount: 1987, openingTime: "12:00", closingTime: "00:00", features: ["vip","wine_cellar","private_room"], coverImage: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&q=75", depositRequired: true, depositAmount: 3000, maxPartySize: 10, tables: [{id:"t26",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r25", name: "Хлеб Насущный", slug: "hleb-nasushny", description: "Пекарня-ресторан с собственным производством хлеба, круассанов и выпечки. Утренние завтраки, бизнес-ланчи и неспешные ужины в семейной атмосфере. Фирменный хлеб на натуральной закваске.", shortDesc: "Пекарня и ресторан с утренними завтраками", cuisine: ["RUSSIAN","FRENCH"], priceRange: "MODERATE", city: "Москва", address: "ул. Мясницкая, 22/1", avgRating: 4.2, reviewCount: 2345, openingTime: "08:00", closingTime: "22:00", features: ["family_friendly"], coverImage: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=75", depositRequired: false, maxPartySize: 6, tables: [{id:"t27",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r26", name: "Bjorn", slug: "bjorn", description: "Авторский ресторан скандинавской кухни от шеф-повара Никиты Подерягина. Дегустационное меню из 10 подач, построенное на локальных сезонных продуктах с использованием техник ферментации и копчения.", shortDesc: "Скандинавская кухня от шефа Никиты Подерягина", cuisine: ["FUSION"], priceRange: "PREMIUM", city: "Москва", address: "Пятницкая, 3", avgRating: 4.8, reviewCount: 432, openingTime: "12:00", closingTime: "00:00", features: ["tasting_menu","wine_pairing"], coverImage: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=75", depositRequired: true, depositAmount: 3000, maxPartySize: 6, tables: [{id:"t28",label:"1",minCapacity:2,maxCapacity:4,tableType:"VIP"}] },
  { id: "r27", name: "Техникум", slug: "tehnikum", description: "Гастрономический бар на Патриарших с коктейльной картой мирового уровня. Авторская кухня фьюжн с акцентом на уличную еду в современном прочтении. Живая музыка по пятницам и субботам.", shortDesc: "Гастрономический бар на Патриках", cuisine: ["FUSION","AMERICAN"], priceRange: "MODERATE", city: "Москва", address: "Спиридоньевский пер., 9", avgRating: 4.3, reviewCount: 876, openingTime: "18:00", closingTime: "02:00", features: ["live_music"], coverImage: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=600&q=75", depositRequired: false, maxPartySize: 6, tables: [{id:"t29",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r28", name: "AQ Kitchen", slug: "aq-kitchen", description: "Авторская кухня испанского шефа Адриана Кетгласа. Средиземноморские мотивы с использованием продуктов российских фермеров. Дегустационное меню с парными винами, открытая кухня театрального формата.", shortDesc: "Авторская кухня Адриана Кетгласа", cuisine: ["FUSION","FRENCH"], priceRange: "PREMIUM", city: "Москва", address: "ул. Б. Грузинская, 69", avgRating: 4.6, reviewCount: 765, openingTime: "12:00", closingTime: "00:00", features: ["tasting_menu","wine_list"], coverImage: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=600&q=75", depositRequired: true, depositAmount: 2000, maxPartySize: 8, tables: [{id:"t30",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r29", name: "Матрёшка", slug: "matryoshka", description: "Ресторан русской кухни в современном прочтении с панорамным видом. Русские сезонные продукты, авторские десерты, приватные залы для банкетов. Популярное место для корпоративных мероприятий.", shortDesc: "Русская кухня в современной интерпретации", cuisine: ["RUSSIAN"], priceRange: "PREMIUM", city: "Москва", address: "Кутузовский пр., 2/1", avgRating: 4.4, reviewCount: 1234, openingTime: "12:00", closingTime: "00:00", features: ["private_room","parking"], coverImage: "https://images.unsplash.com/photo-1543353071-10c8ba85a904?w=600&q=75", depositRequired: false, maxPartySize: 10, tables: [{id:"t31",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r30", name: "La Piazza", slug: "la-piazza", description: "Итальянская траттория на Невском проспекте Санкт-Петербурга. Аутентичная пицца из дровяной печи, паста ручной работы и тирамису по классическому рецепту. Летняя веранда с видом на Невский.", shortDesc: "Итальянская траттория в центре", cuisine: ["ITALIAN"], priceRange: "MODERATE", city: "Санкт-Петербург", address: "Невский пр., 44", avgRating: 4.4, reviewCount: 2345, openingTime: "11:00", closingTime: "23:00", features: ["outdoor_seating","wine_list","live_music"], coverImage: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=600&q=75", depositRequired: false, maxPartySize: 10, tables: [{id:"t32",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r31", name: "Каре", slug: "kare-spb", description: "Стейк-хаус в центре Санкт-Петербурга с отборным мясом из Аргентины, Австралии и Новой Зеландии. Собственная камера созревания, гриль Josper и впечатляющий винный погреб.", shortDesc: "Стейки и мясо на углях", cuisine: ["STEAKHOUSE"], priceRange: "PREMIUM", city: "Санкт-Петербург", address: "Гороховая ул., 14", avgRating: 4.5, reviewCount: 987, openingTime: "12:00", closingTime: "00:00", features: ["wine_cellar"], coverImage: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=75", depositRequired: true, depositAmount: 1500, maxPartySize: 8, tables: [{id:"t33",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r32", name: "Краб Хаус", slug: "krab-haus", description: "Ресторан морепродуктов на набережной Сочи с террасой и видом на Черное море. Свежие крабы, мидии и устрицы из акватории Черного моря. Живая музыка и закаты над морем создают незабываемую атмосферу.", shortDesc: "Крабы и морепродукты Черного моря", cuisine: ["SEAFOOD"], priceRange: "PREMIUM", city: "Сочи", address: "Курортный пр., 12", avgRating: 4.3, reviewCount: 1567, openingTime: "12:00", closingTime: "23:00", features: ["sea_view","terrace","parking"], coverImage: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=75", depositRequired: true, depositAmount: 1000, maxPartySize: 12, tables: [{id:"t34",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
  { id: "r33", name: "Винотека 3/9", slug: "vinoteka-39", description: "Уютный винный бар на Навагинской улице Сочи. Более 200 позиций вин из России и мира, авторские закуски от шефа. Живая музыка по вечерам и дегустации для ценителей вина.", shortDesc: "Винный бар с авторскими закусками", cuisine: ["FUSION","FRENCH"], priceRange: "MODERATE", city: "Сочи", address: "ул. Навагинская, 7", avgRating: 4.6, reviewCount: 654, openingTime: "16:00", closingTime: "02:00", features: ["wine_list","live_music"], coverImage: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=75", depositRequired: false, maxPartySize: 6, tables: [{id:"t35",label:"1",minCapacity:2,maxCapacity:4,tableType:"STANDARD"}] },
];

export function getAvailableSlots(restaurantId: string, date: string, guestCount: number) {
  const restaurant = MOCK_RESTAURANTS.find((r) => r.id === restaurantId);
  if (!restaurant) return [];
  const suitableTables = restaurant.tables.filter((t) => t.minCapacity <= guestCount && t.maxCapacity >= guestCount);
  if (suitableTables.length === 0) return [];
  const [openH] = restaurant.openingTime.split(":").map(Number);
  const [closeH] = restaurant.closingTime.split(":").map(Number);
  const adjustedCloseH = closeH === 0 ? 24 : closeH;
  const slots: { time: string; tables: typeof suitableTables; isPeak: boolean }[] = [];
  for (let h = openH; h < adjustedCloseH - 1; h++) {
    for (const m of [0, 30]) {
      const timeStr = `${String(h % 24).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
      const isPeak = h >= 18 && h <= 21;
      const dateHash = date.split("-").reduce((a, b) => a + parseInt(b), 0);
      const slotHash = (dateHash + h * 60 + m) % 7;
      const availableTables = suitableTables.filter((_, i) => (slotHash + i) % 3 !== 0);
      if (availableTables.length > 0) slots.push({ time: timeStr, tables: availableTables, isPeak });
    }
  }
  return slots;
}

export type MockRestaurant = (typeof MOCK_RESTAURANTS)[number];
export type MockTable = MockRestaurant["tables"][number];
